// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // CLI (migrate/studio) precisa de conexão direta, não da transaction
    // pooler que o app usa em runtime — ver DIRECT_URL no .env.
    url: process.env["DIRECT_URL"],
  },
});
